# Generated by Django 3.2.4 on 2021-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_category', models.CharField(default='', max_length=50)),
                ('product_subcategory', models.CharField(default='', max_length=50)),
                ('product_img', models.ImageField(upload_to='pics')),
                ('product_description', models.CharField(max_length=200)),
                ('product_price', models.IntegerField(default=0)),
            ],
        ),
    ]
