# Generated by Django 3.2.5 on 2021-07-02 12:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_auto_20210702_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cutomer',
            new_name='Customer',
        ),
    ]
