# Generated by Django 3.2.5 on 2021-07-05 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_cutomer_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='trasaction_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer', unique=True),
        ),
    ]
