# Generated by Django 3.2.5 on 2021-07-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_shipping_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trasaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
