# Generated by Django 3.2.5 on 2021-10-06 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_trasaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
