# Generated by Django 3.2.6 on 2021-10-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20211025_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='shipping',
        ),
    ]
