# Generated by Django 3.2.6 on 2021-10-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
