# Generated by Django 3.2.5 on 2022-01-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
