# Generated by Django 3.2.5 on 2022-01-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_rename_data_added_orderitem_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_added',
            new_name='data_added',
        ),
    ]
