# Generated by Django 3.2.5 on 2022-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_rename_date_added_orderitem_data_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trasaction_id',
            field=models.CharField(default='0000000', max_length=200, null=True),
        ),
    ]
