# Generated by Django 3.2.5 on 2022-01-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_order_trasaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trasaction_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
